# ==============================================================
# Configuración de conexión a Azure SQL Server
# ==============================================================
spring.datasource.url=jdbc:sqlserver://proyectointegrador.database.windows.net:1433;databaseName=ProyectoIntegrador;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=sqladmin
spring.datasource.password=ProyInt2
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==============================================================
# Configuración de JPA / Hibernate
# ==============================================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Obligar a Hibernate a usar los nombres exactos de las tablas y columnas (Evita que convierta CreatedAt a created_at)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl